// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AimoClient is the client API for Aimo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AimoClient interface {
	GetPeriod(ctx context.Context, in *GetPeriodRequest, opts ...grpc.CallOption) (*GetPeriodResponse, error)
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	PostUserInfo(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*PostUserInfoResponse, error)
}

type aimoClient struct {
	cc grpc.ClientConnInterface
}

func NewAimoClient(cc grpc.ClientConnInterface) AimoClient {
	return &aimoClient{cc}
}

func (c *aimoClient) GetPeriod(ctx context.Context, in *GetPeriodRequest, opts ...grpc.CallOption) (*GetPeriodResponse, error) {
	out := new(GetPeriodResponse)
	err := c.cc.Invoke(ctx, "/grpc_sample.aimo/getPeriod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aimoClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, "/grpc_sample.aimo/getUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aimoClient) PostUserInfo(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*PostUserInfoResponse, error) {
	out := new(PostUserInfoResponse)
	err := c.cc.Invoke(ctx, "/grpc_sample.aimo/postUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AimoServer is the server API for Aimo service.
// All implementations must embed UnimplementedAimoServer
// for forward compatibility
type AimoServer interface {
	GetPeriod(context.Context, *GetPeriodRequest) (*GetPeriodResponse, error)
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
	PostUserInfo(context.Context, *UserInfo) (*PostUserInfoResponse, error)
	mustEmbedUnimplementedAimoServer()
}

// UnimplementedAimoServer must be embedded to have forward compatible implementations.
type UnimplementedAimoServer struct {
}

func (UnimplementedAimoServer) GetPeriod(context.Context, *GetPeriodRequest) (*GetPeriodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeriod not implemented")
}
func (UnimplementedAimoServer) GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedAimoServer) PostUserInfo(context.Context, *UserInfo) (*PostUserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostUserInfo not implemented")
}
func (UnimplementedAimoServer) mustEmbedUnimplementedAimoServer() {}

// UnsafeAimoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AimoServer will
// result in compilation errors.
type UnsafeAimoServer interface {
	mustEmbedUnimplementedAimoServer()
}

func RegisterAimoServer(s grpc.ServiceRegistrar, srv AimoServer) {
	s.RegisterService(&Aimo_ServiceDesc, srv)
}

func _Aimo_GetPeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AimoServer).GetPeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_sample.aimo/getPeriod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AimoServer).GetPeriod(ctx, req.(*GetPeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aimo_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AimoServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_sample.aimo/getUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AimoServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aimo_PostUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AimoServer).PostUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_sample.aimo/postUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AimoServer).PostUserInfo(ctx, req.(*UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// Aimo_ServiceDesc is the grpc.ServiceDesc for Aimo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Aimo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_sample.aimo",
	HandlerType: (*AimoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getPeriod",
			Handler:    _Aimo_GetPeriod_Handler,
		},
		{
			MethodName: "getUserInfo",
			Handler:    _Aimo_GetUserInfo_Handler,
		},
		{
			MethodName: "postUserInfo",
			Handler:    _Aimo_PostUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/aimo.proto",
}
